LOG_LEVEL_DEBUG = 0
LOG_LEVEL_INFO = 1
LOG_LEVEL_WARNING = 2
LOG_LEVEL_ERROR = 3

TIME_INTERVAL = 1.0
LOG_PATH = "log/"
LOG_LEVEL = LOG_LEVEL_DEBUG
LOG_FILE = "yyyy-mm-dd hh:mm:ss.log"
ENABLE_PERFORMANCE_DISPLAY = True

SYSTEM_INFO = {}
PROCESS_INFO = []

MAIN_PID = 0
LAST_PID = 0
